# Generated by Django 2.2.1 on 2019-07-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopFresh1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='收货地址')),
                ('recver', models.CharField(blank=True, max_length=32, null=True, verbose_name='收件人')),
                ('recver_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='收件人电话')),
                ('post_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮编')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('connect_address', models.TextField(blank=True, null=True, verbose_name='联系地址')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, verbose_name='订单编号')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('order_time', models.IntegerField(verbose_name='订单时间')),
                ('order_price', models.FloatField(verbose_name='订单总价')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='订单地址')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='订单所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_number', models.IntegerField(verbose_name='商品购买数量')),
                ('goods_total', models.FloatField(verbose_name='商品总价')),
                ('goods_store', models.IntegerField(verbose_name='商店id')),
                ('goods_order_time', models.IntegerField(verbose_name='商品订单时间')),
                ('goods_image', models.ImageField(upload_to='', verbose_name='商品图')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Order', verbose_name='订单编号(多对一)')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(blank=True, null=True, verbose_name='货物id')),
                ('goods_number', models.IntegerField(default=1, verbose_name='货物数量')),
                ('goods_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名称')),
                ('goods_price', models.FloatField(blank=True, null=True, verbose_name='商品价格')),
                ('goods_image', models.ImageField(blank=True, null=True, upload_to='shopfresh1/images', verbose_name='商品图片')),
                ('goods_total', models.FloatField(verbose_name='总价')),
                ('goods_under', models.IntegerField(default=1, verbose_name='商品状态')),
                ('goods_addtime', models.FloatField(blank=True, null=True, verbose_name='添加时间')),
                ('goods_carts', models.FloatField(blank=True, default=1, null=True, verbose_name='商品数量')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='买家id')),
                ('store_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ShopFresh1.Store', verbose_name='商店id')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='用户id'),
        ),
    ]
