# Generated by Django 2.2.1 on 2019-07-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='买家id')),
                ('goods_id', models.IntegerField(blank=True, null=True, verbose_name='货物id')),
                ('goods_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名称')),
                ('goods_price', models.FloatField(blank=True, null=True, verbose_name='商品价格')),
                ('goods_image', models.ImageField(blank=True, null=True, upload_to='shopfresh1/images', verbose_name='商品图片')),
                ('goods_under', models.IntegerField(default=1, verbose_name='商品状态')),
                ('goods_addtime', models.FloatField(blank=True, null=True, verbose_name='添加时间')),
            ],
        ),
    ]
