# Generated by Django 2.2.1 on 2019-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20190728_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods_carts',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='商品数量'),
        ),
    ]
