# Generated by Django 2.2.1 on 2019-07-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart_goods_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_cart',
            new_name='user_id',
        ),
    ]
