# Generated by Django 2.2.1 on 2019-07-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190728_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user_ids',
        ),
    ]
