# Generated by Django 2.2.1 on 2019-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_auto_20190728_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='买家id'),
            preserve_default=False,
        ),
    ]
