# Generated by Django 2.2.1 on 2019-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopFresh1', '0002_auto_20190725_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='buyer/images'),
        ),
    ]
